### PR TITLE
Add assets

### LINKED ISSUE #1: Design a logo
Current logo was generated through some online logo generator, it will be good if a dedicated logo is present.

### PR DESCRIPTION
**Pull request by maitreyav**
Resolves #1

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
thanx for the contribution, it will take a little time to review it. :smile:

**Comment by maitreyav** [comment]
Welcome @Anupam-dagar, I love the project. May I know how you got this name?😄
 Do give a feedback.

**Comment by Anupam-dagar** [comment]
@maitreyav it will be good if you can add some kind of color transition or gradient and a little more minimalist.Nice work with the logo.
Coming to how I got this name, I was registering a domain name in a hackathon and it just stuck me :stuck_out_tongue:

**Comment by maitreyav** [comment]
@Anupam-dagar, I see. I think you should go with this name. 😄

Yes, at one point I was thinking to use gradient to make the geometric shape look more inline with current trends.  Are you talking about adding gradient on the layers in logo or background?

**Comment by Anupam-dagar** [comment]
I think in the background, take a look at Instagram's logo to get what I am trying to say.Go with the trend.

**Comment by Anupam-dagar** [comment]
Great :+1: 
can you provide 3 logos something like this
https://raw.githubusercontent.com/Anupam-dagar/Portfolio-Generator/9dca6542b6c7109323b2a0624aa60366ae1f564f/assets/hoxnox_specs.png
one with text below logo,
one with text on right side of logo and
one with text only.
And I'll merge the PR :smile:

**Comment by maitreyav** [comment]
@Anupam-dagar, I will add it this week, 😄

**Comment by Anupam-dagar** [comment]
yeah sure, no problem

**Comment by maitreyav** [comment]
@Anupam-dagar, I'd like to know your thoughts on the new Logo proportions. During the design process, I switched many gradients, this was the one the I liked second best: 

[](https://postimg.org/image/7whmf0vhd7/)

**Comment by Anupam-dagar** [comment]
This one looks better.
Push this one and I'll merge.After that, you can introduce further changes in other PR's.

**Comment by maitreyav** [comment]
@Anupam-dagar, Sure.

**Comment by maitreyav** [comment]
@Anupam-dagar, Thanks! 😄  It felt amazing to be part of the logo design process. I'm glad it went well.

**Pull request merged**
