### PR TITLE
Update images

### PR DESCRIPTION
**Pull request by maitreyav**
## **Changelog**
-  Updated images used for background, banners, avatar & user-icon. 

###  **New gradient blends**
- home1 & user profile: 4FC0E8 → 74EBD5
-    Hoxnox_banner1: 959494 → BC9065

 

Hey @Anupam-dagar, I'm doing it in phases to make sure everything fits in-line with the new logo specs. 😄

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@maitreyav thanx for the contribution, but this one has a lot of variation in colors.I will have to make some major changes to accommodate these images.Let the images remain same as of now.

**Comment by maitreyav** [comment]
Sure, @Anupam-dagar. I was just testing how it will look visually appealing & unique with different blends as the user progresses. 

The current Windows 8.1 hero image felt out of place with the current logo.

 I feel there's bit inconsistency in typography and colours of UI elements aren't going well with the backgrounds. I'll be happy to contribute on that. What you say?

**Comment by Anupam-dagar** [comment]
yeah I didn't paid any attention to typography while developing it.Sure you can suggest some good typography.

**Comment by maitreyav** [comment]
Open Sans seems good, in my opinion. Also, Raleway. I have a mockup in mind for the homepage.

**Comment by maitreyav** [comment]
I'll be sharing some concepts for the homepage and more in coming days.

**Pull request closed without merging**
