### PR TITLE
8 add 500 server html

### PR DESCRIPTION
**Pull request by arnazmursidp**
#8 create 500 server down page

### CODE REVIEW

**Comment by arnazmursidp** [comment]
screenshot from 2017-09-29 17-20-28

**Comment by Anupam-dagar** [comment]
It can be made better. Include name of website and little improvement in design would make it good.

**Comment by arnazmursidp** [comment]
okay will do!

**Comment by arnazmursidp** [comment]
revsision

**Comment by arnazmursidp** [comment]
how about this one? if there are still need some improvements just tell me

**Comment by Anupam-dagar** [comment]
include homepage yellow background and only go back button
I would suggest you to use bootstrap to make sure it is responsive, or you can do by making a copy of homepage code and working on it.

**Comment by arnazmursidp** [comment]
oh okay i'll try

**Comment by arnazmursidp** [comment]
screenshot from 2017-10-06 22-22-48

**Comment by arnazmursidp** [comment]
I already made the content with boostrap, please review it and notify me

**Comment by Anupam-dagar** [comment]
LGTM :+1: 
It will work fine for now.

**Pull request merged**
