### PR TITLE
Creating a new PR with revised page

### PR DESCRIPTION
**Pull request by Divy123**

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
too many unneccessary file, remove them
static file (css, js,images) should go here
https://github.com/Anupam-dagar/Portfolio-Generator/tree/master/portfolio/static

html should go here
https://github.com/Anupam-dagar/Portfolio-Generator/tree/master/portfolio/templates/portfolio

**Comment by Divy123** [comment]
@Anupam-dagar please look into it.
.

**Comment by Anupam-dagar** [comment]
dont't push any folder, files which i think will do will be html, css and js, no other file, font awesome is already linked in website.

**Comment by Divy123** [comment]
Done

**Pull request merged**
