### PR TITLE
new homepage template added

### PR DESCRIPTION
**Pull request by hacker1x1x1**
issue #28 resolved

### CODE REVIEW

**Comment by gauthamzz** [comment]
how many files are you adding, 😄 dont you think its bigger than the size of the project and its a bit too much.

**Comment by mubaris** [comment]
Codacy is saying that you're adding "110 extra issues" 😄

**Comment by hacker1x1x1** [comment]
I just created a new homepage as asked by @Anupam-dagar.

**Comment by Anupam-dagar** [comment]
that's right, codacy checks if not passed should atleast produce less issues.
Coming to file changed "125", I can't merge it with that many changes, keep only neccessary files i.e html of homepage,css,js and required images, anything not in use should not be present.

**Comment by gauthamzz** [comment]
well you need to solve the codacy issues 😄 and 110 doesnt look that good.

@Anupam-dagar i thought you didnt like codacy 😄

**Comment by hacker1x1x1** [comment]
I just added the whole content present inside the template I downloaded
What should I do now @Anupam-dagar @gauthamzz ?

**Comment by Anupam-dagar** [comment]
hahahaa, only first encounter was bad :stuck_out_tongue: @gauthamzz

**Comment by hacker1x1x1** [comment]
it has passes all the tests @Anupam-dagar

**Pull request closed without merging**
