### PR TITLE
#7  Pull request on error page

### PR DESCRIPTION
**Pull request by kunalvishnoi**
adding 404 error page  on issue #7 
screenshot 97

### CODE REVIEW

**Comment by kunalvishnoi** [comment]
animated 404 error page is updated..

**Comment by Anupam-dagar** [comment]
please share a screenshot

**Comment by kunalvishnoi** [comment]
screenshot 98

**Comment by kunalvishnoi** [comment]
is it okay or required some changes @Anupam-dagar ?

**Comment by Anupam-dagar** [comment]
take a look at conversation here
https://github.com/Anupam-dagar/Portfolio-Generator/pull/12

**Pull request closed without merging**
